const page1 = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
      genre_ids: [28, 12, 878],
      id: 634649,
      original_language: "en",
      original_title: "Spider-Man: No Way Home",
      overview:
        "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
      popularity: 13195.451,
      poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
      release_date: "2021-12-15",
      title: "Spider-Man: No Way Home",
      video: false,
      vote_average: 8.5,
      vote_count: 6054,
    },
    {
      adult: false,
      backdrop_path: "/k2twTjSddgLc1oFFHVibfxp2kQV.jpg",
      genre_ids: [28, 12, 14, 878],
      id: 524434,
      original_language: "en",
      original_title: "Eternals",
      overview:
        "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.",
      popularity: 9373.581,
      poster_path: "/bcCBq9N1EMo3daNIjWJ8kYvrQm6.jpg",
      release_date: "2021-11-03",
      title: "Eternals",
      video: false,
      vote_average: 7.3,
      vote_count: 3559,
    },
    {
      adult: false,
      backdrop_path: "/qBLEWvJNVsehJkEJqIigPsWyBse.jpg",
      genre_ids: [16, 10751, 14, 35, 12],
      id: 585083,
      original_language: "en",
      original_title: "Hotel Transylvania: Transformania",
      overview:
        "When Van Helsing's mysterious invention, the \"Monsterfication Ray,\" goes haywire, Drac and his monster pals are all transformed into humans, and Johnny becomes a monster. In their new mismatched bodies, Drac and Johnny must team up and race across the globe to find a cure before it's too late, and before they drive each other crazy.",
      popularity: 7213.45,
      poster_path: "/teCy1egGQa0y8ULJvlrDHQKnxBL.jpg",
      release_date: "2022-01-13",
      title: "Hotel Transylvania: Transformania",
      video: false,
      vote_average: 7.7,
      vote_count: 1153,
    },
    {
      adult: false,
      backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
      genre_ids: [16, 35, 10751, 14],
      id: 568124,
      original_language: "en",
      original_title: "Encanto",
      overview:
        "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
      popularity: 5036.143,
      poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
      release_date: "2021-11-24",
      title: "Encanto",
      video: false,
      vote_average: 7.8,
      vote_count: 3472,
    },
    {
      adult: false,
      backdrop_path: "/o76ZDm8PS9791XiuieNB93UZcRV.jpg",
      genre_ids: [27, 28, 878],
      id: 460458,
      original_language: "en",
      original_title: "Resident Evil: Welcome to Raccoon City",
      overview:
        "Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.",
      popularity: 4765.246,
      poster_path: "/7uRbWOXxpWDMtnsd2PF3clu65jc.jpg",
      release_date: "2021-11-24",
      title: "Resident Evil: Welcome to Raccoon City",
      video: false,
      vote_average: 6.1,
      vote_count: 1028,
    },
    {
      adult: false,
      backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
      genre_ids: [35, 16, 10751, 10402],
      id: 438695,
      original_language: "en",
      original_title: "Sing 2",
      overview:
        "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
      popularity: 4593.267,
      poster_path: "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
      release_date: "2021-12-01",
      title: "Sing 2",
      video: false,
      vote_average: 8.3,
      vote_count: 1364,
    },
    {
      adult: false,
      backdrop_path: "/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
      genre_ids: [35, 14, 12],
      id: 425909,
      original_language: "en",
      original_title: "Ghostbusters: Afterlife",
      overview:
        "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
      popularity: 4555.726,
      poster_path: "/sg4xJaufDiQl7caFEskBtQXfD4x.jpg",
      release_date: "2021-11-11",
      title: "Ghostbusters: Afterlife",
      video: false,
      vote_average: 7.8,
      vote_count: 1558,
    },
    {
      adult: false,
      backdrop_path: "/t4To8feUSysyBs4tlBAbXIrKlCv.jpg",
      genre_ids: [28, 53],
      id: 860623,
      original_language: "en",
      original_title: "Last Man Down",
      overview:
        "After civilization succumbs to a deadly pandemic and his wife is murdered, a special forces soldier abandons his duty and becomes a hermit in the Nordic wilderness. Years later, a wounded woman appears on his doorstep. She's escaped from a lab and her pursuers believe her blood is the key to a worldwide cure. He's hesitant to get involved, but all doubts are cast aside when he discovers her pursuer is none other than Commander Stone, the man that murdered his wife some years ago.",
      popularity: 4385.755,
      poster_path: "/1qRZ8821TCz49bpQ8PQtB2gbavp.jpg",
      release_date: "2021-10-19",
      title: "Last Man Down",
      video: false,
      vote_average: 6.6,
      vote_count: 154,
    },
    {
      adult: false,
      backdrop_path: "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
      genre_ids: [878, 28, 12],
      id: 624860,
      original_language: "en",
      original_title: "The Matrix Resurrections",
      overview:
        "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
      popularity: 3588.016,
      poster_path: "/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
      release_date: "2021-12-16",
      title: "The Matrix Resurrections",
      video: false,
      vote_average: 6.9,
      vote_count: 2510,
    },
    {
      adult: false,
      backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
      genre_ids: [878, 28, 12],
      id: 580489,
      original_language: "en",
      original_title: "Venom: Let There Be Carnage",
      overview:
        "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
      popularity: 3103.826,
      poster_path: "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
      release_date: "2021-09-30",
      title: "Venom: Let There Be Carnage",
      video: false,
      vote_average: 7.1,
      vote_count: 6014,
    },
    {
      adult: false,
      backdrop_path: "/2Jp2RIwJ3Dt7vamkTt7llVJ7uY.jpg",
      genre_ids: [53, 9648, 18],
      id: 916740,
      original_language: "en",
      original_title: "Brazen",
      overview:
        "Mystery writer Grace Miller has killer instincts when it comes to motive - and she'll need every bit of expertise to help solve her sister's murder.",
      popularity: 2867.381,
      poster_path: "/7e4n1GfC9iky9VQzH3cDQz9wYpO.jpg",
      release_date: "2022-01-13",
      title: "Brazen",
      video: false,
      vote_average: 4.8,
      vote_count: 153,
    },
    {
      adult: false,
      backdrop_path: "/dK12GIdhGP6NPGFssK2Fh265jyr.jpg",
      genre_ids: [28, 35, 80, 53],
      id: 512195,
      original_language: "en",
      original_title: "Red Notice",
      overview:
        "An Interpol-issued Red Notice is a global alert to hunt and capture the world's most wanted. But when a daring heist brings together the FBI's top profiler and two rival criminals, there's no telling what will happen.",
      popularity: 2229.534,
      poster_path: "/lAXONuqg41NwUMuzMiFvicDET9Y.jpg",
      release_date: "2021-11-04",
      title: "Red Notice",
      video: false,
      vote_average: 6.8,
      vote_count: 2806,
    },
    {
      adult: false,
      backdrop_path: "/AmLpWYm9R3Ur2FLPgj5CH3wR8wp.jpg",
      genre_ids: [878, 53],
      id: 739413,
      original_language: "en",
      original_title: "Mother/Android",
      overview:
        "Georgia and her boyfriend Sam go on a treacherous journey to escape their country, which is caught in an unexpected war with artificial intelligence. Days away from the arrival of their first child, the couple must face No Man’s Land—a stronghold of the android uprising—in hopes of reaching safety before giving birth.",
      popularity: 2271.007,
      poster_path: "/rO3nV9d1wzHEWsC7xgwxotjZQpM.jpg",
      release_date: "2021-12-17",
      title: "Mother/Android",
      video: false,
      vote_average: 5.8,
      vote_count: 330,
    },
    {
      adult: false,
      backdrop_path: "/cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
      genre_ids: [28, 12, 14],
      id: 566525,
      original_language: "en",
      original_title: "Shang-Chi and the Legend of the Ten Rings",
      overview:
        "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
      popularity: 2070.184,
      poster_path: "/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
      release_date: "2021-09-01",
      title: "Shang-Chi and the Legend of the Ten Rings",
      video: false,
      vote_average: 7.8,
      vote_count: 5342,
    },
    {
      adult: false,
      backdrop_path: "/srJ7haOhfykoPOYPQrstOaFem08.jpg",
      genre_ids: [28],
      id: 811592,
      original_language: "en",
      original_title: "One Shot",
      overview:
        "An elite squad of Navy SEAL's, on a covert mission to transport a prisoner off a CIA black site island prison, are trapped when insurgents attack while trying to rescue the same prisoner.",
      popularity: 2009.808,
      poster_path: "/3OXiTjU30gWtqxmx4BU9RVp2OTv.jpg",
      release_date: "2021-11-05",
      title: "One Shot",
      video: false,
      vote_average: 6.8,
      vote_count: 113,
    },
    {
      adult: false,
      backdrop_path: "/mo57hzhW3BcZL1f7MNteWKHsmlN.jpg",
      genre_ids: [28, 53],
      id: 763788,
      original_language: "en",
      original_title: "Dangerous",
      overview:
        "A reformed sociopath heads to a remote island after the death of his brother. Soon after his arrival, the island falls under siege from a deadly gang of mercenaries, and when he discovers their role in his brother’s demise, he sets out on a relentless quest for vengeance.",
      popularity: 1755.692,
      poster_path: "/vTtkQGC7qKlSRQJZYtAWAmYdH0A.jpg",
      release_date: "2021-11-05",
      title: "Dangerous",
      video: false,
      vote_average: 6.6,
      vote_count: 127,
    },
    {
      adult: false,
      backdrop_path: "/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg",
      genre_ids: [16, 28, 12, 14],
      id: 635302,
      original_language: "ja",
      original_title: "劇場版「鬼滅の刃」無限列車編",
      overview:
        "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
      popularity: 1400.692,
      poster_path: "/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
      release_date: "2020-10-16",
      title: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train",
      video: false,
      vote_average: 8.4,
      vote_count: 2070,
    },
    {
      adult: false,
      backdrop_path: "/A6K6Y39vYsYboyKiiXwcPR6Q6tM.jpg",
      genre_ids: [10770, 9648, 53, 35],
      id: 922885,
      original_language: "es",
      original_title: "Laura y el misterio del asesino inesperado",
      overview:
        "After years of leave, Laura Lebrel returns to action. Lydia asks him for help on a case: Eugenio Ortiz, Laura's former instructor, has been murdered. But a new detective, Hector, finds evidence that incriminates Laura. She asks to be allowed to find the killer and Lydia gives her 24 hours to solve the case before arresting her.",
      popularity: 1655.249,
      poster_path: "/p6T9g5a227cUs4rlTlaxo8QAqIf.jpg",
      release_date: "2022-01-13",
      title: "Laura y el misterio del asesino inesperado",
      video: false,
      vote_average: 6.9,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/7esxXkFyl0dVD7ViR0Q6fK5VeXB.jpg",
      genre_ids: [28, 53, 80],
      id: 787310,
      original_language: "en",
      original_title: "Survive the Game",
      overview:
        "When cop David is injured in a drug bust gone wrong, his partner Cal chases the two criminals who shot him. They all land at a remote farm owned by troubled vet Eric, and as Cal and Eric plot their defense, more of the gang arrives - along with a wounded David. Outnumbered, the three heroes must use stealth, smarts, and good shooting to take down the drug-dealing mob.",
      popularity: 1633.862,
      poster_path: "/xF1uc2pEf34X2G41wvZaF5H0V7C.jpg",
      release_date: "2021-10-08",
      title: "Survive the Game",
      video: false,
      vote_average: 5.8,
      vote_count: 85,
    },
    {
      adult: false,
      backdrop_path: "/1Wlwnhn5sXUIwlxpJgWszT622PS.jpg",
      genre_ids: [16, 35, 10751],
      id: 585245,
      original_language: "en",
      original_title: "Clifford the Big Red Dog",
      overview:
        "As Emily struggles to fit in at home and at school, she discovers a small red puppy who is destined to become her best friend. When Clifford magically undergoes one heck of a growth spurt, becomes a gigantic dog and attracts the attention of a genetics company, Emily and her Uncle Casey have to fight the forces of greed as they go on the run across New York City. Along the way, Clifford affects the lives of everyone around him and teaches Emily and her uncle the true meaning of acceptance and unconditional love.",
      popularity: 1308.582,
      poster_path: "/oifhfVhUcuDjE61V5bS5dfShQrm.jpg",
      release_date: "2021-11-10",
      title: "Clifford the Big Red Dog",
      video: false,
      vote_average: 7.4,
      vote_count: 933,
    },
  ],
  total_pages: 32077,
  total_results: 641538,
};

const page2 = {
  page: 2,
  results: [
    {
      adult: false,
      backdrop_path: "/9fzNf2QcsHVvdx5g5QUOgAWpADw.jpg",
      genre_ids: [18, 27, 9648],
      id: 516329,
      original_language: "en",
      original_title: "Antlers",
      overview:
        "A small-town Oregon teacher and her brother, the local sheriff, discover a young student is harbouring a dangerous secret that could have frightening consequences.",
      popularity: 1103.284,
      poster_path: "/cMch3tiexw3FdOEeZxMWVel61Xg.jpg",
      release_date: "2021-10-28",
      title: "Antlers",
      video: false,
      vote_average: 6.4,
      vote_count: 413,
    },
    {
      adult: false,
      backdrop_path: "/1BqX34aJS5J8PefVnQSfQIEPfkl.jpg",
      genre_ids: [80, 28, 53],
      id: 826749,
      original_language: "en",
      original_title: "Fortress",
      overview:
        "The story revolves around a top-secret resort for retired U.S. intelligence officers. A group of criminals led by Balzary breach the compound, hellbent on revenge on Robert, forcing the retired officer and his son to save the day.",
      popularity: 1316.238,
      poster_path: "/vQxtoPJVfpHgL7DCg9hQFZKDWJa.jpg",
      release_date: "2021-12-17",
      title: "Fortress",
      video: false,
      vote_average: 6.4,
      vote_count: 126,
    },
    {
      adult: false,
      backdrop_path: "/xGrTm3J0FTafmuQ85vF7ZCw94x6.jpg",
      genre_ids: [18, 36, 12],
      id: 589761,
      original_language: "ru",
      original_title: "Чернобыль",
      overview:
        "The aftermath of a shocking explosion at the Chernobyl nuclear power station made hundreds of people sacrifice their lives to clean up the site of the catastrophe and to successfully prevent an even bigger disaster that could have turned a large part of the European continent into an uninhabitable exclusion zone. This is their story.",
      popularity: 1143.14,
      poster_path: "/AmJLuHjxPdIJO6vmymeWADG6jK5.jpg",
      release_date: "2021-04-15",
      title: "Chernobyl: Abyss",
      video: false,
      vote_average: 6.2,
      vote_count: 282,
    },
    {
      adult: false,
      backdrop_path: "/7h5WAPAcUzOWpp2jrwHBB48790j.jpg",
      genre_ids: [16, 14],
      id: 843241,
      original_language: "ja",
      original_title: "劇場版 七つの大罪 光に呪われし者たち",
      overview:
        'With the help of the "Dragon Sin of Wrath" Meliodas and the worst rebels in history, the Seven Deadly Sins, the "Holy War", in which four races, including Humans, Goddesses, Fairies and Giants fought against the Demons, is finally over. At the cost of the "Lion Sin of Pride" Escanor\'s life, the Demon King was defeated and the world regained peace. After that, each of the Sins take their own path.',
      popularity: 1253.775,
      poster_path: "/k0ThmZQl5nHe4JefC2bXjqtgYp0.jpg",
      release_date: "2021-07-02",
      title: "The Seven Deadly Sins: Cursed by Light",
      video: false,
      vote_average: 8,
      vote_count: 287,
    },
    {
      adult: false,
      backdrop_path: "/r2GAjd4rNOHJh6i6Y0FntmYuPQW.jpg",
      genre_ids: [12, 28, 53],
      id: 370172,
      original_language: "en",
      original_title: "No Time to Die",
      overview:
        "Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
      popularity: 850.677,
      poster_path: "/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
      release_date: "2021-09-29",
      title: "No Time to Die",
      video: false,
      vote_average: 7.5,
      vote_count: 3277,
    },
    {
      adult: false,
      backdrop_path: "/sLWUtbrpiLp23a0XDSiUiltdFPJ.jpg",
      genre_ids: [28, 12, 14],
      id: 1930,
      original_language: "en",
      original_title: "The Amazing Spider-Man",
      overview:
        "Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents' disappearance – leading him directly to Oscorp and the lab of Dr. Curt Connors, his father's former partner. As Spider-Man is set on a collision course with Connors' alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.",
      popularity: 894.825,
      poster_path: "/fSbqPbqXa7ePo8bcnZYN9AHv6zA.jpg",
      release_date: "2012-06-23",
      title: "The Amazing Spider-Man",
      video: false,
      vote_average: 6.6,
      vote_count: 14351,
    },
    {
      adult: false,
      backdrop_path: "/Aqp47Dbz8f1wnVU1qKvFFXQFROr.jpg",
      genre_ids: [53, 27],
      id: 811072,
      original_language: "es",
      original_title: "Dos",
      overview:
        "Two people, a man and a woman, wake up naked and with their abdomens attached to each other.",
      popularity: 940.718,
      poster_path: "/5P7QwmoYl70tsRZ8e0VnI9RI1MF.jpg",
      release_date: "2021-07-23",
      title: "Two",
      video: false,
      vote_average: 5.3,
      vote_count: 166,
    },
    {
      adult: false,
      backdrop_path: "/mFbS5TwN95BcSEfiztdchLgTQ0v.jpg",
      genre_ids: [28, 18, 36],
      id: 617653,
      original_language: "en",
      original_title: "The Last Duel",
      overview:
        "King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire, Jacques Le Gris, by challenging him to a duel.",
      popularity: 833.794,
      poster_path: "/zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg",
      release_date: "2021-10-13",
      title: "The Last Duel",
      video: false,
      vote_average: 7.6,
      vote_count: 1566,
    },
    {
      adult: false,
      backdrop_path: "/mRZDHjArYNWpOv06kxRK1cduQKh.jpg",
      genre_ids: [27, 53],
      id: 754934,
      original_language: "en",
      original_title: "Son",
      overview:
        "When a young boy contracts a mysterious illness, his mother must decide how far she will go to protect him from terrifying forces in her past.",
      popularity: 1014.509,
      poster_path: "/4fl6EdtMp6p0RKJgESdFti1J3dC.jpg",
      release_date: "2021-08-06",
      title: "Son",
      video: false,
      vote_average: 6.2,
      vote_count: 70,
    },
    {
      adult: false,
      backdrop_path: "/pxOiKwRvNp3zFOiuwpYpzlbmEgC.jpg",
      genre_ids: [16, 35, 12, 10751],
      id: 459151,
      original_language: "en",
      original_title: "The Boss Baby: Family Business",
      overview:
        "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",
      popularity: 874.796,
      poster_path: "/kv2Qk9MKFFQo4WQPaYta599HkJP.jpg",
      release_date: "2021-07-01",
      title: "The Boss Baby: Family Business",
      video: false,
      vote_average: 7.6,
      vote_count: 1719,
    },
    {
      adult: false,
      backdrop_path: "/zlj0zHo67xXoj7hvwGtaKRkSdBV.jpg",
      genre_ids: [12, 18],
      id: 728526,
      original_language: "en",
      original_title: "Encounter",
      overview:
        "A decorated Marine goes on a rescue mission to save his two young sons from an unhuman threat. As their journey takes them in increasingly dangerous directions, the boys will need to leave their childhoods behind.",
      popularity: 983.192,
      poster_path: "/tUkY0WxffPZ9PoyC62PIyyUMGnt.jpg",
      release_date: "2021-12-03",
      title: "Encounter",
      video: false,
      vote_average: 6.4,
      vote_count: 209,
    },
    {
      adult: false,
      backdrop_path: "/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg",
      genre_ids: [35, 28, 12, 878],
      id: 550988,
      original_language: "en",
      original_title: "Free Guy",
      overview:
        "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.",
      popularity: 818.018,
      poster_path: "/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg",
      release_date: "2021-08-11",
      title: "Free Guy",
      video: false,
      vote_average: 7.7,
      vote_count: 4709,
    },
    {
      adult: false,
      backdrop_path: "/wYMbnrdRCREjNLwFlG5SLWzBjui.jpg",
      genre_ids: [878, 12],
      id: 438631,
      original_language: "en",
      original_title: "Dune",
      overview:
        "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
      popularity: 824.127,
      poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
      release_date: "2021-09-15",
      title: "Dune",
      video: false,
      vote_average: 7.9,
      vote_count: 5664,
    },
    {
      adult: false,
      backdrop_path: "/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg",
      genre_ids: [28, 12, 14],
      id: 436969,
      original_language: "en",
      original_title: "The Suicide Squad",
      overview:
        "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
      popularity: 742.164,
      poster_path: "/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg",
      release_date: "2021-07-28",
      title: "The Suicide Squad",
      video: false,
      vote_average: 7.7,
      vote_count: 5379,
    },
    {
      adult: false,
      backdrop_path: "/mPyiNWS0upEG1mGKOKyCQSoZpnp.jpg",
      genre_ids: [28, 12, 14],
      id: 102382,
      original_language: "en",
      original_title: "The Amazing Spider-Man 2",
      overview:
        "For Peter Parker, life is busy. Between taking out the bad guys as Spider-Man and spending time with the person he loves, Gwen Stacy, high school graduation cannot come quickly enough. Peter has not forgotten about the promise he made to Gwen’s father to protect her by staying away, but that is a promise he cannot keep. Things will change for Peter when a new villain, Electro, emerges, an old friend, Harry Osborn, returns, and Peter uncovers new clues about his past.",
      popularity: 710.001,
      poster_path: "/c3e9e18SSlvFd1cQaGmUj5tqL5P.jpg",
      release_date: "2014-04-16",
      title: "The Amazing Spider-Man 2",
      video: false,
      vote_average: 6.5,
      vote_count: 10555,
    },
    {
      adult: false,
      backdrop_path: "/usaZV7KB6Man9Rm9TyDAeQf7uVD.jpg",
      genre_ids: [27, 9648, 53],
      id: 646385,
      original_language: "en",
      original_title: "Scream",
      overview:
        "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
      popularity: 624.46,
      poster_path: "/kZNHR1upJKF3eTzdgl5V8s8a4C3.jpg",
      release_date: "2022-01-12",
      title: "Scream",
      video: false,
      vote_average: 7.3,
      vote_count: 327,
    },
    {
      adult: false,
      backdrop_path: "/oE6bhqqVFyIECtBzqIuvh6JdaB5.jpg",
      genre_ids: [878, 18, 12],
      id: 522402,
      original_language: "en",
      original_title: "Finch",
      overview:
        "On a post-apocalyptic Earth, a robot, built to protect the life of his dying creator's beloved dog, learns about life, love, friendship, and what it means to be human.",
      popularity: 796.447,
      poster_path: "/jKuDyqx7jrjiR9cDzB5pxzhJAdv.jpg",
      release_date: "2021-11-04",
      title: "Finch",
      video: false,
      vote_average: 8.1,
      vote_count: 1856,
    },
    {
      adult: false,
      backdrop_path: "/x78cvxbmpBNcHON7x3Iv8vih5Sj.jpg",
      genre_ids: [16, 35, 10751],
      id: 774741,
      original_language: "en",
      original_title: "Diary of a Wimpy Kid",
      overview:
        "Greg Heffley is a scrawny but ambitious kid with an active imagination and big plans to be rich and famous – he just has to survive middle school first.",
      popularity: 776.328,
      poster_path: "/obg6lWuNaZkoSlwrVG4VVk4SmT.jpg",
      release_date: "2021-12-03",
      title: "Diary of a Wimpy Kid",
      video: false,
      vote_average: 6.8,
      vote_count: 147,
    },
    {
      adult: false,
      backdrop_path: "/tTlAA0REGPXSZPBfWyTW9ipIv1I.jpg",
      genre_ids: [28, 12, 878, 18],
      id: 315635,
      original_language: "en",
      original_title: "Spider-Man: Homecoming",
      overview:
        "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
      popularity: 709.637,
      poster_path: "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
      release_date: "2017-07-05",
      title: "Spider-Man: Homecoming",
      video: false,
      vote_average: 7.4,
      vote_count: 17912,
    },
    {
      adult: false,
      backdrop_path: "/8rft8A9nH43IReybFtYt21ezfMK.jpg",
      genre_ids: [99],
      id: 899082,
      original_language: "en",
      original_title: "Harry Potter 20th Anniversary: Return to Hogwarts",
      overview:
        "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
      popularity: 638.684,
      poster_path: "/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
      release_date: "2022-01-01",
      title: "Harry Potter 20th Anniversary: Return to Hogwarts",
      video: false,
      vote_average: 8.3,
      vote_count: 824,
    },
  ],
  total_pages: 32076,
  total_results: 641517,
};

const pages = [page1, page2];

export const getPopularMovies = (page = 1) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      let result = JSON.parse(JSON.stringify(pages[0]))
      result.page = page
      resolve(result);
    }, 3000);
  });
};

export const getMovieDetails = (id = 0) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve({
        adult: false,
        backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
        belongs_to_collection: {
          id: 531241,
          name: "Spider-Man (Avengers) Collection",
          poster_path: "/nogV4th2P5QWYvQIMiWHj4CFLU9.jpg",
          backdrop_path: "/AvnqpRwlEaYNVL6wzC4RN94EdSd.jpg",
        },
        budget: 200000000,
        genres: [
          {
            id: 28,
            name: "Action",
          },
          {
            id: 12,
            name: "Adventure",
          },
          {
            id: 878,
            name: "Science Fiction",
          },
        ],
        homepage: "https://www.spidermannowayhome.movie",
        id: 634649,
        imdb_id: "tt10872600",
        original_language: "en",
        original_title: "Spider-Man: No Way Home",
        overview:
          "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        popularity: 13195.451,
        poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
        production_companies: [
          {
            id: 420,
            logo_path: "/hUzeosd33nzE5MCNsZxCGEKTXaQ.png",
            name: "Marvel Studios",
            origin_country: "US",
          },
          {
            id: 84041,
            logo_path: "/nw4kyc29QRpNtFbdsBHkRSFavvt.png",
            name: "Pascal Pictures",
            origin_country: "US",
          },
          {
            id: 5,
            logo_path: "/71BqEFAF4V3qjjMPCpLuyJFB9A.png",
            name: "Columbia Pictures",
            origin_country: "US",
          },
        ],
        production_countries: [
          {
            iso_3166_1: "US",
            name: "United States of America",
          },
        ],
        release_date: "2021-12-15",
        revenue: 1691110988,
        runtime: 148,
        spoken_languages: [
          {
            english_name: "English",
            iso_639_1: "en",
            name: "English",
          },
          {
            english_name: "Tagalog",
            iso_639_1: "tl",
            name: "",
          },
        ],
        status: "Released",
        tagline: "The Multiverse unleashed.",
        title: "Spider-Man: No Way Home",
        video: false,
        vote_average: 8.5,
        vote_count: 6111,
      });
    }, 3000);
  });
};
